language: groovy
jdk:
  - oraclejdk8

script: ./grailsw refresh-dependencies
     && ./grailsw maven-install
     && ./grailsw maven-deploy --repository=releases

#after_success:
 # - ./deploy.sh

# The encryption label is the unique key used in the environment
# variables set up when calling `travis encrypt-file` on the SSH key
env:
  global:
    - ENCRYPTION_LABEL="b9829a5785d1"
    - GIT_NAME="subaan"
    - GIT_EMAIL="abdulsubaanbtech@gmail.com"
    - DEPLOY_BRANCH="master"

